//! Tick processing for the simulation.
//!
//! The tick processor is a pure function that takes GameState and produces Events.
//! All game systems are processed here: production, consumption, population needs,
//! random events, etc.

use crate::domain::GameState;
use crate::events::{EventType, GameEvent};
use crate::simulation::production::{process_building_production, ProductionResult, ProductionError};
use crate::content::ContentLoader;
use std::collections::HashMap;

/// Process a single simulation tick.
///
/// This is the main simulation step function. It:
/// 1. Checks if the simulation is paused  
/// 2. Advances the game clock by one tick
/// 3. Processes all game systems (production, population, events, etc.)
/// 4. Returns all events generated during the tick
///
/// # Arguments
/// * `state` - Mutable reference to game state to update
/// * `content` - Content loader with recipe definitions
///
/// # Returns
/// Vector of events generated during the tick. Returns empty vec if paused.
///
/// # Note
/// Event IDs are managed by the caller (typically EventStore in the server layer).
/// This function creates events with placeholder event_id=0.
pub fn process_tick(state: &mut GameState, content: &ContentLoader) -> Vec<GameEvent> {
    // Don't process if paused
    if state.is_paused() {
        return vec![];
    }

    let mut events = vec![];

    // Advance the clock
    state.advance_tick();
    let new_tick = state.current_tick();

    // Generate tick event (event_id will be assigned by EventStore)
    events.push(GameEvent::new(
        0, // Placeholder event_id
        new_tick,
        EventType::TurnAdvanced {
            turn_number: new_tick,
        },
    ));

    // Process production chains (buildings produce resources)
    let production_events = process_production_tick(state, content, new_tick);
    events.extend(production_events);

    // TODO: Process other game systems:
    // - Population consumption (colonists consume food, water, oxygen)
    // - Power grid balancing (batteries charge/discharge)
    // - Research progress (if tech system implemented)
    // - Random events (anomalies, failures, conflicts)
    // - Idle safety checks (auto-pause if critical resources depleted)

    events
}

/// Process production for all operational buildings across all sites.
///
/// For each building with an active recipe:
/// 1. Validates inputs are available
/// 2. Consumes inputs if starting a production cycle
/// 3. Advances recipe progress
/// 4. Produces outputs when recipe completes
/// 5. Generates events for all state changes
///
/// # Arguments
/// * `state` - Mutable game state
/// * `content` - Content loader with recipe definitions
/// * `tick` - Current tick number for event timestamps
///
/// # Returns
/// Vector of events generated by production processing
fn process_production_tick(state: &mut GameState, content: &ContentLoader, tick: u64) -> Vec<GameEvent> {
    let mut events = Vec::new();

    // Collect system/site/body/building combinations to process
    // This avoids complex borrow checker issues
    let mut to_process = Vec::new();
    
    for (system_id, system) in &state.galaxy.systems {
        for (site_id, site) in &system.sites {
            let body_id = site.body_id;
            let building_ids: Vec<_> = site.buildings.keys().copied().collect();
            
            for building_id in building_ids {
                to_process.push((*system_id, *site_id, body_id, building_id));
            }
        }
    }

    // Now process each building
    for (system_id, site_id, body_id, building_id) in to_process {
        // Get mutable references to all needed parts
        let system = match state.galaxy.systems.get_mut(&system_id) {
            Some(s) => s,
            None => continue,
        };
        
        let site = match system.sites.get_mut(&site_id) {
            Some(s) => s,
            None => continue,
        };
        
        let body = match system.bodies.get_mut(&body_id) {
            Some(b) => b,
            None => continue,
        };

        // Process this building's production
        let result = process_building_production(building_id, site, body, content);
        
        match result {
            Ok(ProductionResult::InProgress { building_id: _, recipe_id, progress_ticks, processing_time_ticks }) => {
                // Generate progress event
                events.push(GameEvent::new(
                    0,
                    tick,
                    EventType::RecipeProgressed {
                        site_id,
                        building_id,
                        recipe_id,
                        progress_ticks,
                        total_ticks: processing_time_ticks,
                        tick,
                    },
                ));
            }
            Ok(ProductionResult::Completed { building_id: _, recipe_id, inputs_consumed: _, outputs_produced }) => {
                // Generate completion event
                events.push(GameEvent::new(
                    0,
                    tick,
                    EventType::RecipeCompleted {
                        site_id,
                        building_id,
                        recipe_id: recipe_id.clone(),
                        tick,
                    },
                ));
                
                // Generate outputs produced event
                events.push(GameEvent::new(
                    0,
                    tick,
                    EventType::ProductionOutputsProduced {
                        site_id,
                        building_id,
                        recipe_id,
                        outputs: outputs_produced,
                        tick,
                    },
                ));
            }
            Ok(ProductionResult::Halted { building_id: _, recipe_id, reason }) => {
                // Convert ProductionError to string
                let reason_str = match reason {
                    ProductionError::InsufficientResource { resource, needed, available } => {
                        format!("Insufficient {}: need {:.1}, have {:.1}", resource, needed, available)
                    }
                    ProductionError::InsufficientStorage { resource, amount, available } => {
                        format!("Insufficient storage for {}: need {:.1}, have {:.1}", resource, amount, available)
                    }
                    ProductionError::MissingOrDepletedDeposit { resource } => {
                        format!("Missing or depleted deposit for {}", resource)
                    }
                    ProductionError::MappingError(err) => {
                        format!("Resource mapping error: {}", err)
                    }
                    ProductionError::RecipeError(err) => {
                        format!("Recipe error: {}", err)
                    }
                    ProductionError::BuildingNotOperational(bid) => {
                        format!("Building {:?} is not operational", bid)
                    }
                    ProductionError::NoRecipeAssigned(bid) => {
                        format!("No recipe assigned to building {:?}", bid)
                    }
                };
                
                // Generate halted event
                events.push(GameEvent::new(
                    0,
                    tick,
                    EventType::ProductionHalted {
                        site_id,
                        building_id,
                        recipe_id,
                        reason: reason_str,
                        tick,
                    },
                ));
            }
            Ok(ProductionResult::Idle { building_id: _ }) => {
                // No event for idle buildings (no recipe assigned or paused)
            }
            Err(err) => {
                // Log domain errors but don't halt simulation
                // In production, this would use tracing::error!
                eprintln!("Production error at site {:?}, building {:?}: {:?}", 
                          site_id, building_id, err);
            }
        }
    }

    events
}

/// Process multiple simulation ticks in batch.
///
/// This is useful for fast-forward scenarios or catching up after loading.
/// Each tick is processed sequentially with full event generation.
///
/// # Arguments
/// * `state` - Mutable reference to game state to update
/// * `content` - Content loader with recipe definitions
/// * `count` - Number of ticks to process
///
/// # Returns
/// Vector of all events generated across all ticks.
pub fn process_ticks(state: &mut GameState, content: &ContentLoader, count: u64) -> Vec<GameEvent> {
    let mut all_events = vec![];
    
    for _ in 0..count {
        let tick_events = process_tick(state, content);
        all_events.extend(tick_events);
    }
    
    all_events
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::content::ContentLoader;

    fn create_test_content() -> ContentLoader {
        ContentLoader::new()
    }

    #[test]
    fn test_process_tick_advances_clock() {
        let mut state = GameState::new("Test".to_string(), 42);
        let content = create_test_content();
        let initial_tick = state.current_tick();
        
        let events = process_tick(&mut state, &content);
        
        assert_eq!(state.current_tick(), initial_tick + 1);
        assert_eq!(events.len(), 1);
        match &events[0].event_type {
            EventType::TurnAdvanced { turn_number } => {
                assert_eq!(*turn_number, initial_tick + 1);
            }
            _ => panic!("Expected TurnAdvanced event"),
        }
    }

    #[test]
    fn test_process_tick_when_paused() {
        let mut state = GameState::new("Test".to_string(), 42);
        let content = create_test_content();
        state.pause();
        let initial_tick = state.current_tick();
        
        let events = process_tick(&mut state, &content);
        
        assert_eq!(state.current_tick(), initial_tick); // No change
        assert_eq!(events.len(), 0); // No events
    }

    #[test]
    fn test_process_multiple_ticks() {
        let mut state = GameState::new("Test".to_string(), 42);
        let content = create_test_content();
        let initial_tick = state.current_tick();
        let count = 10;
        
        let events = process_ticks(&mut state, &content, count);
        
        assert_eq!(state.current_tick(), initial_tick + count);
        assert_eq!(events.len(), count as usize); // One event per tick
    }

    #[test]
    fn test_process_ticks_respects_pause() {
        let mut state = GameState::new("Test".to_string(), 42);
        let content = create_test_content();
        let initial_tick = state.current_tick();
        
        // Process 3 ticks normally
        process_ticks(&mut state, &content, 3);
        assert_eq!(state.current_tick(), initial_tick + 3);
        
        // Pause and try to process more
        state.pause();
        let events = process_ticks(&mut state, &content, 5);
        
        // Should not have advanced
        assert_eq!(state.current_tick(), initial_tick + 3);
        assert_eq!(events.len(), 0);
    }

    #[test]
    fn test_event_contains_turn_number() {
        let mut state = GameState::new("Test".to_string(), 42);
        let content = create_test_content();
        
        let events = process_tick(&mut state, &content);
        
        assert_eq!(events[0].turn_number, 1);
        match &events[0].event_type {
            EventType::TurnAdvanced { turn_number } => {
                assert_eq!(*turn_number, 1);
            }
            _ => panic!("Expected TurnAdvanced event"),
        }
    }

    #[test]
    fn test_multiple_ticks_increment_turn_number() {
        let mut state = GameState::new("Test".to_string(), 42);
        let content = create_test_content();
        
        // Process 5 ticks
        let events = process_ticks(&mut state, &content, 5);
        
        // Each event should have incrementing turn number
        for (i, event) in events.iter().enumerate() {
            let expected_turn = (i + 1) as u64;
            assert_eq!(event.turn_number, expected_turn);
            match &event.event_type {
                EventType::TurnAdvanced { turn_number } => {
                    assert_eq!(*turn_number, expected_turn);
                }
                _ => panic!("Expected TurnAdvanced event"),
            }
        }
    }

    #[test]
    fn test_production_integrated_with_tick_empty_state() {
        // Test that production processing is called during tick (even with empty state)
        let mut state = GameState::new("Test".to_string(), 42);
        let content = create_test_content();
        
        // Process a tick - should not panic
        let events = process_tick(&mut state, &content);
        
        // Should have TurnAdvanced event at minimum
        assert!(!events.is_empty());
        assert!(matches!(events[0].event_type, EventType::TurnAdvanced { .. }));
    }

    #[test]
    fn test_production_events_generated_during_multiple_ticks() {
        let mut state = GameState::new("Test".to_string(), 42);
        let content = create_test_content();
        
        // Process multiple ticks - even with empty state, should not panic
        let events = process_ticks(&mut state, &content, 3);
        
        // Verify event structure - should have 3 TurnAdvanced events for empty state
        assert_eq!(events.len(), 3);
        for (i, event) in events.iter().enumerate() {
            assert_eq!(event.turn_number, (i + 1) as u64);
            assert!(matches!(event.event_type, EventType::TurnAdvanced { .. }));
        }
    }

    #[test]
    fn test_tick_processing_respects_game_state() {
        let mut state = GameState::new("Test".to_string(), 42);
        let content = create_test_content();
        
        // Initially not paused
        assert!(!state.is_paused());
        
        // Process a tick
        let events1 = process_tick(&mut state, &content);
        assert_eq!(events1.len(), 1); // TurnAdvanced
        assert_eq!(state.current_tick(), 1);
        
        // Pause and try to process
        state.pause();
        let events2 = process_tick(&mut state, &content);
        assert_eq!(events2.len(), 0); // No events when paused
        assert_eq!(state.current_tick(), 1); // Tick didn't advance
        
        // Resume and process again
        state.resume();
        let events3 = process_tick(&mut state, &content);
        assert_eq!(events3.len(), 1); // TurnAdvanced
        assert_eq!(state.current_tick(), 2);
    }
}
