[package]
name = "outpost_tauri"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "outpost_tauri_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "outpost_tauri"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
outpost_core = { path = "../outpost_core" }
tauri = { version = "2", features = ["devtools"] }
tauri-plugin-shell = "2"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { version = "1", features = ["full"] }

[lints]
workspace = true
