use actix_web::web;

use super::handlers;

pub fn configure(cfg: &mut web::ServiceConfig) {
    cfg.service(
        web::scope("")
            .route("/", web::get().to(handlers::index))
            .route("/dashboard", web::get().to(handlers::dashboard))
            // Colonies overview (V5)
            .route("/colonies", web::get().to(handlers::colonies_handler::colonies_list))
            // Site detail routes (V5)
            .route("/site/{id}", web::get().to(handlers::site_handlers::site_detail))
            .route("/site/{id}/buildings", web::get().to(handlers::site_handlers::site_buildings_tab))
            .route("/site/{id}/construction", web::get().to(handlers::site_handlers::site_construction_tab))
            .route("/site/{id}/resources", web::get().to(handlers::site_handlers::site_resources_tab))
            .route("/site/{id}/resources/set", web::post().to(handlers::site_handlers::admin_set_resource))
            .route("/site/{id}/labor", web::get().to(handlers::labor_handlers::site_labor_tab))
            .route("/site/{id}/labor/set", web::post().to(handlers::site_handlers::admin_set_labor))
            .route("/site/{id}/labor/set-workers", web::post().to(handlers::labor_handlers::set_building_workers))
            .route("/site/{id}/building/{bid}/demolish", web::post().to(handlers::site_handlers::demolish_building))
            .route("/site/{id}/building/{bid}/assign", web::post().to(handlers::labor_handlers::assign_labor))
            .route("/site/{id}/building/{bid}/deallocate", web::post().to(handlers::labor_handlers::deallocate_labor))
            .route("/site/{id}/build", web::post().to(handlers::site_handlers::start_construction))
            .route("/site/{id}/construction/{job_id}/cancel", web::post().to(handlers::site_handlers::cancel_construction))
            .route("/site/{id}/construction/{job_id}/pause", web::post().to(handlers::site_handlers::toggle_pause_construction))
            // Legacy routes temporarily disabled during V5 migration
            // .route("/colony/{id}", web::get().to(handlers::view_colony))
            // .route("/colony/create", web::post().to(handlers::create_colony))
            // .route("/colony/{id}/building", web::post().to(handlers::construct_building))
            // .route("/colony/{colony_id}/building/{building_id}/upgrade", web::post().to(handlers::upgrade_building))
            // .route("/colony/{colony_id}/building/{building_id}/repair", web::post().to(handlers::colony_actions::repair_building))
            // .route("/colony/{colony_id}/building/{building_id}/toggle", web::post().to(handlers::colony_actions::toggle_building))
            // .route("/colony/{id}/building/{building_id}/allocate_labor", web::post().to(handlers::colony_actions::allocate_labor))
            // .route("/colony/{id}/building/{building_id}/deallocate_labor", web::post().to(handlers::colony_actions::deallocate_labor))
            // .route("/colony/{id}/turn", web::post().to(handlers::advance_turn))
            .route("/map", web::get().to(handlers::admin_handlers::view_starmap))
            // Systems views
            .route("/systems", web::get().to(handlers::system_handlers::systems_list))
            .route("/systems/{id}", web::get().to(handlers::system_handlers::system_detail))
            // Found Colony flow
            .route("/sites/create", web::post().to(handlers::admin_handlers::found_colony))
            // Admin section
            .route("/admin", web::get().to(handlers::admin_handlers::admin_index))
            .route("/admin/systems", web::get().to(handlers::admin_handlers::admin_systems_list))
            .route("/admin/systems/create", web::post().to(handlers::admin_handlers::admin_systems_create))
            .route("/admin/systems/{id}", web::get().to(handlers::admin_handlers::admin_system_detail))
            .route("/admin/systems/{id}/delete", web::post().to(handlers::admin_handlers::admin_systems_delete))
            .route("/admin/systems/{id}/toggle-explored", web::post().to(handlers::admin_handlers::admin_systems_toggle_explored))
            .route("/admin/systems/{id}/bodies/create", web::post().to(handlers::admin_handlers::admin_system_bodies_create))
            .route("/admin/systems/{id}/bodies/{body_id}/edit", web::post().to(handlers::admin_handlers::admin_system_bodies_edit))
            .route("/admin/systems/{id}/bodies/{body_id}/delete", web::post().to(handlers::admin_handlers::admin_system_bodies_delete))
            .route("/admin/systems/{id}/sites/create", web::post().to(handlers::admin_handlers::admin_system_sites_create))
            .route("/admin/systems/{id}/sites/{site_id}/edit", web::post().to(handlers::admin_handlers::admin_system_sites_edit))
            .route("/admin/systems/{id}/sites/{site_id}/delete", web::post().to(handlers::admin_handlers::admin_system_sites_delete))
            .route("/admin/bodies", web::get().to(handlers::admin_handlers::admin_bodies_list))
            .route("/admin/bodies/create", web::post().to(handlers::admin_handlers::admin_bodies_create))
            .route("/admin/bodies/{id}/edit", web::post().to(handlers::admin_handlers::admin_bodies_edit))
            .route("/admin/bodies/{id}/delete", web::post().to(handlers::admin_handlers::admin_bodies_delete))
            .route("/admin/sites", web::get().to(handlers::admin_handlers::admin_sites_list))
            .route("/admin/sites/create", web::post().to(handlers::admin_handlers::admin_sites_create))
            .route("/admin/sites/{id}/edit", web::post().to(handlers::admin_handlers::admin_sites_edit))
            .route("/admin/sites/{id}/delete", web::post().to(handlers::admin_handlers::admin_sites_delete))
            .route("/admin/events", web::get().to(handlers::admin_handlers::admin_events_list))
            .route("/admin/events/create", web::post().to(handlers::admin_handlers::admin_events_create))
            .route("/admin/events/{index}/delete", web::post().to(handlers::admin_handlers::admin_events_delete))
            .route("/admin/buildings", web::get().to(handlers::admin_handlers::admin_buildings_list))
            .route("/admin/content/resources", web::get().to(handlers::admin_handlers::admin_content_resources))
            .route("/admin/content/resources/create", web::post().to(handlers::admin_handlers::admin_content_resources_create))
            .route("/admin/content/resources/{id}", web::get().to(handlers::admin_handlers::admin_content_resource_detail))
            .route("/admin/content/resources/{id}/edit", web::post().to(handlers::admin_handlers::admin_content_resources_edit))
            .route("/admin/content/resources/{id}/delete", web::post().to(handlers::admin_handlers::admin_content_resources_delete))
            .route("/admin/content/buildings", web::get().to(handlers::admin_handlers::admin_content_buildings))
            .route("/admin/content/buildings/create", web::post().to(handlers::admin_handlers::admin_content_buildings_create))
            .route("/admin/content/buildings/{id}", web::get().to(handlers::admin_handlers::admin_content_building_detail))
            .route("/admin/content/buildings/{id}/edit", web::post().to(handlers::admin_handlers::admin_content_buildings_edit))
            .route("/admin/content/buildings/{id}/delete", web::post().to(handlers::admin_handlers::admin_content_buildings_delete))
            .route("/admin/content/recipes", web::get().to(handlers::admin_handlers::admin_content_recipes))
            .route("/admin/content/recipes/create", web::post().to(handlers::admin_handlers::admin_content_recipes_create))
            .route("/admin/content/recipes/{id}", web::get().to(handlers::admin_handlers::admin_content_recipe_detail))
            .route("/admin/content/recipes/{id}/edit", web::post().to(handlers::admin_handlers::admin_content_recipes_edit))
            .route("/admin/content/recipes/{id}/delete", web::post().to(handlers::admin_handlers::admin_content_recipes_delete))
            // Export / Import routes
            .route("/admin/export/{table}", web::get().to(handlers::import_export_handlers::export_table))
            .route("/admin/export/{table}/csv", web::get().to(handlers::import_export_handlers::export_table_csv))
            .route("/admin/import/{table}", web::post().to(handlers::import_export_handlers::import_table))
            // Time control API routes
            .route("/api/time/status", web::get().to(handlers::time_control::get_time_status))
            .route("/api/time/pause", web::post().to(handlers::time_control::pause_simulation))
            .route("/api/time/resume", web::post().to(handlers::time_control::resume_simulation))
            .route("/api/time/toggle", web::post().to(handlers::time_control::toggle_pause))
            .route("/api/time/speed", web::post().to(handlers::time_control::set_speed))
            .route("/api/time/idle-safety/enable", web::post().to(handlers::time_control::enable_idle_safety))
            .route("/api/time/idle-safety/disable", web::post().to(handlers::time_control::disable_idle_safety))
            // Resource polling API
            .route("/api/resources/summary", web::get().to(handlers::resource_api_handlers::resource_summary))
            // Power grid routes
            .route("/site/{id}/power", web::get().to(handlers::power_handlers::site_power_tab))
            .route("/site/{id}/building/{bid}/power/toggle", web::post().to(handlers::power_handlers::toggle_building_power))
            // Life support routes
            .route("/site/{id}/life-support", web::get().to(handlers::life_support_handlers::site_life_support_tab))
            // Event log routes
            .route("/events", web::get().to(handlers::event_handlers::event_log_page))
            .route("/api/events/ticker", web::get().to(handlers::event_handlers::event_ticker))
            .route("/api/events/badges", web::get().to(handlers::event_handlers::event_badges))
            .route("/site/{id}/events/{event_id}/choice", web::get().to(handlers::event_handlers::event_choice_modal))
            .route("/site/{id}/events/{event_id}/resolve", web::post().to(handlers::event_handlers::resolve_event_choice))
    );
}
